# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'EvolveAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Google Sign-In
  pod 'GoogleSignIn'
  
  # Facebook Login
  pod 'FBSDKLoginKit'
  
  # Apple Sign-In (built into iOS, no pod needed)
  
  # Supabase Swift (if you want to use the official SDK later)
  # pod 'Supabase'
  
  target 'EvolveAITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EvolveAIUITests' do
    # Pods for testing
  end

end 