#!/bin/zsh

# Script to generate frontend .env with local Supabase credentials
# This is needed because Expo embeds EXPO_PUBLIC_* variables at build time

set -euo pipefail

PROJECT_ROOT="/Users/dheijden003/Library/CloudStorage/OneDrive-PwC/Desktop/Projects/EvolveAI"
FRONTEND_ENV="${PROJECT_ROOT}/frontend/.env"

echo "🔧 Generating frontend .env for local development..."

# Get Supabase credentials from JSON output
SUPABASE_JSON=$(cd "${PROJECT_ROOT}" && supabase status --output json 2>/dev/null || echo "")

if [ -z "$SUPABASE_JSON" ]; then
  echo "❌ Error: Could not get Supabase status. Is Supabase running?"
  echo "   Run: supabase start"
  exit 1
fi

# Extract credentials using python3
if ! command -v python3 >/dev/null 2>&1; then
  echo "❌ Error: python3 not found. Install python3 to continue."
  exit 1
fi

SUPABASE_URL=$(echo "$SUPABASE_JSON" | python3 -c "import sys, json; print(json.load(sys.stdin).get('API_URL', ''))" 2>/dev/null || echo "")
SUPABASE_ANON_KEY=$(echo "$SUPABASE_JSON" | python3 -c "import sys, json; print(json.load(sys.stdin).get('ANON_KEY', ''))" 2>/dev/null || echo "")

if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "❌ Error: Could not extract Supabase credentials"
  exit 1
fi

# Generate .env file for frontend
cat > "$FRONTEND_ENV" <<EOF
# Auto-generated by setup-frontend-env.sh
# DO NOT COMMIT THIS FILE - it contains local development credentials
# Generated: $(date)

# Local Supabase (auto-detected)
EXPO_PUBLIC_SUPABASE_URL=$SUPABASE_URL
EXPO_PUBLIC_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

# Backend URL (local development)
EXPO_PUBLIC_BACKEND_URL=http://127.0.0.1:8000

# Debug mode
EXPO_PUBLIC_DEBUG=false
EOF

echo "✅ Frontend .env generated successfully!"
echo "   EXPO_PUBLIC_SUPABASE_URL: $SUPABASE_URL"
echo "   EXPO_PUBLIC_SUPABASE_ANON_KEY: ${#SUPABASE_ANON_KEY} chars"
echo ""
echo "⚠️  IMPORTANT: You need to RESTART Metro bundler for changes to take effect!"
echo "   Press Ctrl+C in the terminal running start.sh and run it again."

