# Generated by Django 5.2.4 on 2025-07-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='training',
            new_name='WorkoutPlan',
        ),
    ]
