# Generated by Django 5.2.4 on 2025-07-25 14:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_workoutplan_created_at_workoutplan_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
