from pydantic import BaseModel, Field
from typing import List, Optional
from enum import Enum


class QuestionType(str, Enum):
    """Types of questions that can be asked."""
    MULTIPLE_CHOICE = "multiple_choice"
    DROPDOWN = "dropdown"
    FREE_TEXT = "free_text"
    SLIDER = "slider"
    CONDITIONAL_BOOLEAN = "conditional_boolean"
    RATING = "rating"


class QuestionCategory(str, Enum):
    """Categories for grouping questions."""
    TRAINING_EXPERIENCE = "training_experience"
    GOALS_PREFERENCES = "goals_preferences"
    EQUIPMENT_AVAILABILITY = "equipment_availability"
    TIME_COMMITMENT = "time_commitment"
    MEDICAL_HEALTH = "medical_health"
    LIFESTYLE_RECOVERY = "lifestyle_recovery"
    NUTRITION = "nutrition"
    MOTIVATION_COMMITMENT = "motivation_commitment"


class QuestionOption(BaseModel):
    """Option for choice questions."""
    id: str = Field(..., description="Unique identifier for the option")
    text: str = Field(..., description="Display text for the option")
    value: str = Field(..., description="Value to be stored when selected")


class AIQuestion(BaseModel):
    """Individual question generated by AI."""
    id: str = Field(..., description="Unique identifier for the question")
    text: str = Field(..., description="Question text")
    response_type: QuestionType = Field(..., description="Type of response expected")
    options: Optional[List[QuestionOption]] = Field(default=None, description="Options for choice questions")
    required: bool = Field(default=True, description="Whether this question is required")
    category: QuestionCategory = Field(..., description="Category this question belongs to")
    min_value: Optional[float] = Field(default=None, description="Minimum value for slider questions")
    max_value: Optional[float] = Field(default=None, description="Maximum value for slider questions")
    step: Optional[float] = Field(default=1.0, description="Step size for slider questions")
    unit: Optional[str] = Field(default=None, description="Unit of measurement for slider questions (e.g., kg, lbs, minutes)")
    max_length: Optional[int] = Field(default=None, description="Maximum length for text questions")
    placeholder: Optional[str] = Field(default=None, description="Placeholder text for input fields")
    help_text: Optional[str] = Field(default=None, description="Additional help text for the question")


class AIQuestionResponse(BaseModel):
    """Response from AI containing generated questions."""
    questions: List[AIQuestion] = Field(..., description="List of generated questions")
    total_questions: int = Field(..., description="Total number of questions")
    estimated_time_minutes: int = Field(..., description="Estimated time to complete in minutes")
    categories: List[QuestionCategory] = Field(..., description="Categories covered in this question set")


class AIQuestionResponseWithFormatted(BaseModel):
    """Response from AI containing generated questions and formatted responses."""
    questions: List[AIQuestion] = Field(..., description="List of generated questions")
    total_questions: int = Field(..., description="Total number of questions")
    estimated_time_minutes: int = Field(..., description="Estimated time to complete in minutes")
    categories: List[QuestionCategory] = Field(..., description="Categories covered in this question set")
    formatted_responses: str = Field(..., description="Formatted responses for database storage")


class PersonalInfo(BaseModel):
    """Basic personal information."""
    username: str = Field(..., min_length=3, max_length=20, description="User's chosen username")
    age: int = Field(..., ge=13, le=100, description="User's age")
    weight: float = Field(..., gt=0, description="User's weight")
    height: float = Field(..., gt=0, description="User's height")
    weight_unit: str = Field(default="kg", description="Unit for weight (kg or lbs)")
    height_unit: str = Field(default="cm", description="Unit for height (cm or inches)")
    measurement_system: str = Field(default="metric", description="Measurement system preference (metric or imperial)")
    gender: str = Field(..., description="User's gender")
    goal_description: str = Field(..., description="User's goal description in their own words")
    experience_level: str = Field(default="novice", description="User's fitness experience level")


class InitialQuestionsRequest(BaseModel):
    """Request for initial questions generation."""
    personal_info: PersonalInfo = Field(..., description="Basic personal information")
    user_profile_id: Optional[str] = Field(default=None, description="User profile ID for database storage")
    jwt_token: Optional[str] = Field(default=None, description="JWT token for authentication")


class FollowUpQuestionsRequest(BaseModel):
    """Request for follow-up questions generation."""
    personal_info: PersonalInfo = Field(..., description="Basic personal information")
    initial_responses: dict = Field(..., description="Responses to initial questions")
    initial_questions: Optional[List[AIQuestion]] = Field(default=None, description="Initial questions for context")
    user_profile_id: Optional[str] = Field(default=None, description="User profile ID for database storage")
    jwt_token: Optional[str] = Field(default=None, description="JWT token for authentication")


class PlanGenerationRequest(BaseModel):
    """Request for workout plan generation."""
    personal_info: PersonalInfo = Field(..., description="Basic personal information")
    initial_responses: dict = Field(..., description="Responses to initial questions")
    follow_up_responses: dict = Field(..., description="Responses to follow-up questions")
    initial_questions: Optional[List[AIQuestion]] = Field(default=None, description="Initial questions for context")
    follow_up_questions: Optional[List[AIQuestion]] = Field(default=None, description="Follow-up questions for context")
    jwt_token: str = Field(..., description="JWT token for authentication")


class PlanGenerationResponse(BaseModel):
    """Response from workout plan generation."""
    success: bool = Field(..., description="Whether plan generation was successful")
    workout_plan: Optional[dict] = Field(default=None, description="Generated workout plan")
    error: Optional[str] = Field(default=None, description="Error message if unsuccessful")
