"""
Schemas for latency tracking in the training system.
"""

from typing import Optional, Literal
from pydantic import BaseModel, Field
from datetime import datetime


# Type alias for valid event types
EventType = Literal[
    "initial_questions",
    "followup_questions",
    "playbook",
    "initial_plan",
    "feedback_plan",
    "regenerate_plan"
]


class LatencyEvent(BaseModel):
    """
    Schema for a single latency event.
    
    Each event represents one AI operation with its duration and token usage.
    Simple event log structure for easy analytics and cost tracking.
    """
    
    id: Optional[int] = Field(None, description="Database ID of the latency event")
    event: EventType = Field(..., description="Type of AI operation")
    duration_seconds: float = Field(..., description="Duration of the AI API call in seconds", ge=0)
    input_tokens: Optional[int] = Field(None, description="Number of input tokens sent to AI model", ge=0)
    output_tokens: Optional[int] = Field(None, description="Number of output tokens generated by AI model", ge=0)
    total_tokens: Optional[int] = Field(None, description="Total tokens used (input + output)", ge=0)
    model: Optional[str] = Field(None, description="AI model used (e.g., gpt-4o, gpt-4)")
    created_at: Optional[datetime] = Field(None, description="When the event occurred")
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": 1,
                "event": "initial_questions",
                "duration_seconds": 2.5,
                "input_tokens": 1500,
                "output_tokens": 800,
                "total_tokens": 2300,
                "model": "gpt-4o",
                "created_at": "2025-10-30T12:00:00Z",
            }
        }


class LatencyStats(BaseModel):
    """
    Statistics for latency analysis.
    """
    
    operation: str = Field(..., description="Name of the operation")
    count: int = Field(..., description="Number of measurements", ge=0)
    avg_seconds: float = Field(..., description="Average duration in seconds", ge=0)
    min_seconds: float = Field(..., description="Minimum duration in seconds", ge=0)
    max_seconds: float = Field(..., description="Maximum duration in seconds", ge=0)
    p50_seconds: Optional[float] = Field(None, description="Median duration (p50)", ge=0)
    p95_seconds: Optional[float] = Field(None, description="95th percentile duration", ge=0)
    p99_seconds: Optional[float] = Field(None, description="99th percentile duration", ge=0)
    
    class Config:
        json_schema_extra = {
            "example": {
                "operation": "initial_questions",
                "count": 100,
                "avg_seconds": 2.8,
                "min_seconds": 1.2,
                "max_seconds": 5.4,
                "p50_seconds": 2.5,
                "p95_seconds": 4.1,
                "p99_seconds": 5.0,
            }
        }


class LatencySummary(BaseModel):
    """
    Summary of latencies across all operations.
    """
    
    total_records: int = Field(..., description="Total number of latency records", ge=0)
    operations: List[LatencyStats] = Field(
        default_factory=list,
        description="Statistics for each operation",
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "total_records": 100,
                "operations": [
                    {
                        "operation": "initial_questions",
                        "count": 100,
                        "avg_seconds": 2.8,
                        "min_seconds": 1.2,
                        "max_seconds": 5.4,
                        "p50_seconds": 2.5,
                        "p95_seconds": 4.1,
                        "p99_seconds": 5.0,
                    }
                ],
            }
        }

