from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum


class QuestionType(str, Enum):
    """Types of questions that can be asked."""
    MULTIPLE_CHOICE = "multiple_choice"
    DROPDOWN = "dropdown"
    FREE_TEXT = "free_text"
    SLIDER = "slider"
    CONDITIONAL_BOOLEAN = "conditional_boolean"
    RATING = "rating"


class QuestionCategory(str, Enum):
    """Categories for grouping questions."""
    TRAINING_EXPERIENCE = "training_experience"
    GOALS_PREFERENCES = "goals_preferences"
    EQUIPMENT_AVAILABILITY = "equipment_availability"
    TIME_COMMITMENT = "time_commitment"
    MEDICAL_HEALTH = "medical_health"
    LIFESTYLE_RECOVERY = "lifestyle_recovery"
    NUTRITION = "nutrition"
    MOTIVATION_COMMITMENT = "motivation_commitment"


class QuestionOption(BaseModel):
    """Option for choice questions."""
    id: str = Field(..., description="Unique identifier for the option")
    text: str = Field(..., description="Display text for the option")
    value: str = Field(..., description="Value to be stored when selected")


class AIQuestion(BaseModel):
    """Individual question generated by AI."""
    id: str = Field(..., description="Unique identifier for the question")
    text: str = Field(..., description="Question text")
    response_type: QuestionType = Field(..., description="Type of response expected")
    options: Optional[List[QuestionOption]] = Field(default=None, description="Options for choice questions")
    required: bool = Field(default=True, description="Whether this question is required")
    category: QuestionCategory = Field(..., description="Category this question belongs to")
    min_value: Optional[float] = Field(default=None, description="Minimum value for slider questions")
    max_value: Optional[float] = Field(default=None, description="Maximum value for slider questions")
    step: Optional[float] = Field(default=1.0, description="Step size for slider questions")
    unit: Optional[str] = Field(default=None, description="Unit of measurement for slider questions (e.g., kg, lbs, minutes)")
    max_length: Optional[int] = Field(default=None, description="Maximum length for text questions")
    placeholder: Optional[str] = Field(default=None, description="Placeholder text for input fields")
    help_text: Optional[str] = Field(default=None, description="Additional help text for the question")


class AIQuestionResponse(BaseModel):
    """Response from AI containing generated questions."""
    questions: List[AIQuestion] = Field(..., description="List of generated questions")
    total_questions: int = Field(..., description="Total number of questions")
    estimated_time_minutes: int = Field(..., description="Estimated time to complete in minutes")
    categories: List[QuestionCategory] = Field(..., description="Categories covered in this question set")
    ai_message: Optional[str] = Field(default=None, description="Personalized AI coach message for this phase")


class AIQuestionResponseWithFormatted(BaseModel):
    """Response from AI containing generated questions and formatted responses."""
    questions: List[AIQuestion] = Field(..., description="List of generated questions")
    total_questions: int = Field(..., description="Total number of questions")
    estimated_time_minutes: int = Field(..., description="Estimated time to complete in minutes")
    categories: List[QuestionCategory] = Field(..., description="Categories covered in this question set")
    formatted_responses: str = Field(..., description="Formatted responses for database storage")
    ai_message: Optional[str] = Field(default=None, description="Personalized AI coach message for this phase")


class PersonalInfo(BaseModel):
    """Basic personal information."""
    username: str = Field(..., min_length=3, max_length=20, description="User's chosen username")
    age: int = Field(..., ge=13, le=100, description="User's age")
    weight: float = Field(..., gt=0, description="User's weight")
    height: float = Field(..., gt=0, description="User's height")
    weight_unit: str = Field(default="kg", description="Unit for weight (kg or lbs)")
    height_unit: str = Field(default="cm", description="Unit for height (cm or inches)")
    measurement_system: str = Field(default="metric", description="Measurement system preference (metric or imperial)")
    gender: str = Field(..., description="User's gender")
    goal_description: str = Field(..., description="User's goal description in their own words")
    experience_level: str = Field(default="novice", description="User's training experience level")


class InitialQuestionsRequest(BaseModel):
    """Request for initial questions generation."""
    personal_info: PersonalInfo = Field(..., description="Basic personal information")
    user_profile_id: Optional[str] = Field(default=None, description="User profile ID for database storage")
    jwt_token: Optional[str] = Field(default=None, description="JWT token for authentication")


class FollowUpQuestionsRequest(BaseModel):
    """Request for follow-up questions generation."""
    personal_info: PersonalInfo = Field(..., description="Basic personal information")
    initial_responses: Dict[str, Any] = Field(..., description="Raw responses to initial questions")
    initial_questions: List[AIQuestion] = Field(..., description="Initial questions from frontend")
    user_profile_id: Optional[str] = Field(default=None, description="User profile ID for database storage")
    jwt_token: Optional[str] = Field(default=None, description="JWT token for authentication")


class TrainingPlanOutlineRequest(BaseModel):
    """Request for training plan outline generation."""
    personal_info: PersonalInfo = Field(..., description="Basic personal information")
    initial_responses: Dict[str, Any] = Field(..., description="Raw responses to initial questions")
    follow_up_responses: Dict[str, Any] = Field(..., description="Raw responses to follow-up questions")
    initial_questions: List[AIQuestion] = Field(..., description="Initial questions from frontend")
    follow_up_questions: List[AIQuestion] = Field(..., description="Follow-up questions from frontend")
    jwt_token: str = Field(..., description="JWT token for authentication")


class PlanGenerationRequest(BaseModel):
    """Request for training plan generation."""
    personal_info: PersonalInfo = Field(..., description="Basic personal information")
    initial_responses: Dict[str, Any] = Field(..., description="Raw responses to initial questions")
    follow_up_responses: Dict[str, Any] = Field(..., description="Raw responses to follow-up questions")
    plan_outline: Optional[dict] = Field(default=None, description="Training plan outline from frontend")
    plan_outline_feedback: Optional[str] = Field(default=None, description="User feedback on plan outline")
    initial_questions: List[AIQuestion] = Field(..., description="Initial questions from frontend")
    follow_up_questions: List[AIQuestion] = Field(..., description="Follow-up questions from frontend")
    jwt_token: str = Field(..., description="JWT token for authentication")


class TrainingPlanOutlineResponse(BaseModel):
    """Response from training plan outline generation."""
    success: bool = Field(..., description="Whether outline generation was successful")
    outline: Optional[dict] = Field(default=None, description="Generated training plan outline")
    error: Optional[str] = Field(default=None, description="Error message if unsuccessful")


class DailyTraining(BaseModel):
    """Daily training structure for training plan outline."""
    day: int = Field(..., description="Day number (1-7)")
    training_name: str = Field(..., description="Name of the training (e.g., 'Upper Body Strength', 'Easy Cardio')")
    description: str = Field(..., description="Explanation in max. 20 words of the day's training which can include items as duration, intensity, muscle groups, heart rate zones, distance, and equipment needed dependent on the training type")
    tags: List[str] = Field(..., description="Tags for categorization (e.g., 'strength', 'cardio', 'recovery', 'high-intensity')")


class TrainingPeriod(BaseModel):
    """Training period structure for training plan outline."""
    period_name: str = Field(..., description="Name of the training period (e.g., 'Foundation Phase', 'Build Phase', 'Peak Phase')")
    duration_weeks: int = Field(..., description="Duration of this period in weeks")
    explanation: str = Field(..., description="Detailed explanation of what this period involves")
    daily_trainings: List[DailyTraining] = Field(..., description="Sample daily trainings for this period")


class TrainingPlanOutline(BaseModel):
    """Structured training plan outline for any sport or athletic discipline."""
    title: str = Field(..., description="Program title in 3 words or less")
    duration_weeks: int = Field(..., description="Total program duration in weeks")
    explanation: str = Field(..., description="High-level overview and explanation of the training plan")
    training_periods: List[TrainingPeriod] = Field(..., description="Training periods breakdown of the program")
    ai_message: Optional[str] = Field(default=None, description="Personalized AI coach message for this phase")


class ExerciseRetrievalDecision(BaseModel):
    """AI's decision on whether to retrieve exercises from database."""
    
    retrieve_exercises: bool = Field(..., description="Whether you need exercises from the database")
    difficulty: Optional[str] = Field(default=None, description="If retrieving exercises, what difficulty level?")
    equipment: Optional[List[str]] = Field(default=None, description="If retrieving exercises, what equipment types?")
    max_exercises: Optional[int] = Field(default=None, description="If retrieving exercises, how many do you need?")
    reasoning: str = Field(..., description="Your reasoning for this decision")
    alternative_approach: Optional[str] = Field(default=None, description="If not using exercises, what approach will you take?")


class PlanGenerationResponse(BaseModel):
    """Response from training plan generation."""
    success: bool = Field(..., description="Whether plan generation was successful")
    training_plan: Optional[dict] = Field(default=None, description="Generated training plan")
    error: Optional[str] = Field(default=None, description="Error message if unsuccessful")
