# Generated by Django 5.2.4 on 2025-07-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=100)),
                ('iconName', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
                ('primaryColorHex', models.CharField(max_length=7)),
            ],
        ),
    ]
