# Generated by Django 5.2.4 on 2025-07-12 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primaryGoal", models.CharField(max_length=200)),
                ("primaryGoalDescription", models.TextField()),
                ("experienceLevel", models.CharField(max_length=50)),
                ("daysPerWeek", models.IntegerField()),
                ("minutesPerSession", models.IntegerField()),
                ("equipment", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                ("weight", models.FloatField()),
                ("weightUnit", models.CharField(max_length=10)),
                ("height", models.FloatField()),
                ("heightUnit", models.CharField(max_length=10)),
                ("gender", models.CharField(max_length=50)),
                ("hasLimitations", models.BooleanField(default=False)),
                ("limitationsDescription", models.TextField(blank=True, null=True)),
                ("trainingSchedule", models.CharField(max_length=200)),
                ("finalChatNotes", models.TextField(blank=True, null=True)),
                (
                    "coach",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.coach",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
