name: Check PR Source Branch

on:
  pull_request:
    branches:
      - main 

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is 'main-dev'
        if: github.head_ref != 'main-dev'
        run: |
          echo "Error: Pull requests to 'main' can only be from the 'main-dev' branch."
          exit 1