# .github/workflows/swift-ci.yml
# This workflow runs tests on the Swift frontend and enforces that
# pull requests to the 'main' branch can only come from 'develop'.

name: Swift CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main and develop branches
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

jobs:
  # This job runs the Swift test suite
  build:
    name: Run Swift Tests
    # Swift projects require macOS runners
    runs-on: macos-latest

    steps:
    # 1. Check out the repository code
    - name: Check out code
      uses: actions/checkout@v4

    # 2. Select the Xcode version
    # You can specify a version or use the latest available on the runner
    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 'latest'

    # 3. Run the tests using xcodebuild
    # IMPORTANT: Replace the following placeholders:
    #   - 'YourSchemeName': The name of your project's scheme (e.g., 'MyApp').
    #   - 'YourProject.xcodeproj': The name of your .xcodeproj file.
    #   - 'platform=iOS Simulator,name=iPhone 14': The destination simulator.
    - name: Run Swift Tests
      run: |
        xcodebuild test \
          -project frontend/EvolveAI.xcodeproj \
          -scheme EvolveAI \
          -destination 'platform=iOS Simulator,name=iPhone 14' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

  # NEW JOB: This job enforces the branch merging rule.
  enforce-branch-naming:
    name: Enforce PR from develop to main
    runs-on: ubuntu-latest
    # This job only runs on Pull Requests that are targeting the 'main' branch.
    if: github.event_name == 'pull_request' && github.base_ref == 'main'

    steps:
      - name: Check source branch name
        run: |
          echo "Pull Request is from ${{ github.head_ref }} to ${{ github.base_ref }}."
          # Check if the head ref (the source branch) is 'develop'.
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "::error ::Pull Requests to 'main' must come from the 'develop' branch. Current source branch is '${{ github.head_ref }}'."
            exit 1
          fi
          echo "PR source branch is correct."
